name: Pull Request

on: pull_request

jobs:
  pull-request:
    name: npm

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
      - name: Set up Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "lts/*"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
