name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: npm

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "lts/*"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn dlx semantic-release
